import pandas as pd
df = pd.read_csv("student_performance.csv")
print("Dataset Information:")
print(df.info())
print("\nStatistics:")
print(df.describe())
print("\nAverage Final Marks:")
print(df["Final_Marks"].mean())
print("\nAverage Attendance:")
print(df["Attendance"].mean())
print("\nHighest Final Marks:")
print(df["Final_Marks"].max())
print("\nLowest Final Marks:")
print(df["Final_Marks"].min())
print("\nPass/Fail:")
print(df["Result"].value_counts())